### ISSUE TITLE
"unresolved external symbol" error on Visual Studio 2015.

### ISSUE THREAD

**Issue by hiz1** [danomatika/ofxLua#44]
Hello, I have an issue for executing ofxLua example on Visual Studio 2015.

When I build the luaExample project, I get the "unresolved external symbol" error.
error LNK2001: unresolved external symbol "_lua_gettop" (_SWIG_Lua_class_register)

Lua libraries are seems to be compiled(obj files are crearted in obj folder), but linker failed.

I'm working on openframeworks 0.9.8 for Windows(Visual Studio 2015).
I cloned ofxLua on addon folder, and ran command "git submodule init", "git submodule init".

Thanks.

**Comment by danomatika** [comment]
Are you sure the lua sources are being built with the addon? It seems like the headers are found but the linker can't find the implementation.

**Comment by hiz1** [comment]
Thanks for reply.
I checked obj/Debug folder, all  lua obj files and ofxLua.obj, ofxLuaBindings.obj, ofxLuaFileWriter.obj, main.obj, ofApp.obj are found.
I wonder why linker can't find lua implementation. Umm...

**Comment by hiz1** [comment]
I finally got it with a non smart way.
I deleted all files in  ofxLua/libs folder, made lua5.3.0-static.lib from lua sources([An Japanese article](https://qiita.com/gpsnmeajp/items/5ae55d8f79d129f7c62b)  helps me).
 and put it in ofxLua/libs folder, and put lauxlib.h, lua.h, lua.hpp, luaconf.h, lualib.h in ofxLua/src, and added below line to ofxlua.h.
`#pragma comment(lib,"../libs/lua5.3.0-static.lib")`

Now I can run the ofxLua example.
Thanks.

**Comment by danomatika** [comment]
Let's keep this open as it *should* work, although I've not tested in Visual Studio personally.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by marcinklimek** [comment]
In such situation check if Visual Studio is compiling code as C, not as C++. You can look at symbols in object files. I had same problem a few days ago. Force Lua files to be compiled as C, ofx projects are C++.

**Comment by danomatika** [comment]
That makes sense. There should be a way to specify this in the addon_config.mk file.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Also, what are the steps to change the compile type for a file in VS? My windows install was hosed and I haven't reinstalled yet.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by marcinklimek** [comment]
On Solution Explorer:
- select C files, e.g. lapi.c + lauxlib.c ...
- right click -> choose Properties
- select C/C++, Advanced from left tree
- change Compile As -> Compile as C Code (/TC)

**Comment by danomatika** [comment]
Thanks. I added this info to the readme for now.
