### ISSUE TITLE
example not compiling on linux debian buster

### ISSUE THREAD

**Issue by adammccartney** [danomatika/ofxLua#64]
Hi there, 

great looking addon, having some trouble getting the libraries to compile on linux debian.

from the ofxLua main directory, I'm running the following on the command line: 

```
projectGenerator -o"/home/adam/openFrameworks" -a"ofxLua" ./luaExample
cd ./luaExample
make > error.log 2>&1
```

produces the following: 

```
Compiling OF library for Release
make[1]: Entering directory '/home/adam/openFrameworks/libs/openFrameworksCompiled/project'
Done!
make[1]: Leaving directory '/home/adam/openFrameworks/libs/openFrameworksCompiled/project'


Compiling luaExample for Release
make[1]: Entering directory '/home/adam/openFrameworks/addons/ofxLua/luaExample'
Linking bin/luaExample for linux64
g++ -o bin/luaExample  obj/linux64/Release/src/ofApp.o obj/linux64/Release/src/main.o  /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/bindings/glmBindings.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/bindings/desktop/ofBindings.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/ofxLua.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/ofxLuaFileWriter.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lstring.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lmem.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lutf8lib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ltable.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lvm.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/loslib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ldump.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/linit.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lbitlib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ldebug.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lzio.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lauxlib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lcode.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lstate.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lapi.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lmathlib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lstrlib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ltablib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lctype.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lcorolib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lgc.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lbaselib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lparser.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/llex.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lundump.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lfunc.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ldblib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/loadlib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lopcodes.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/liolib.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ltm.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/ldo.o /home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/libs/lua/lobject.o  /home/adam/openFrameworks/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -fuse-ld=gold -L/home/adam/openFrameworks/libs/fmod/lib/linux64/ -lfmod /home/adam/openFrameworks/libs/kiss/lib/linux64/libkiss.a /home/adam/openFrameworks/libs/tess2/lib/linux64/libtess2.a   -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lcurl -lglfw -lrtaudio -lpulse-simple -lpulse -lasound -lGLEW -lGLU -lGL -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -ldl -lpthread -lfreeimage -lboost_filesystem -lboost_system -lpugixml -luriparser -lXinerama
/home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/bindings/glmBindings.o:glmBindings.cpp:function _wrap_fma: error: undefined reference to 'glm::vec<2, float, (glm::qualifier)0> glm::fma<glm::vec<2, float, (glm::qualifier)0> >(glm::vec<2, float, (glm::qualifier)0> const&, glm::vec<2, float, (glm::qualifier)0> const&, glm::vec<2, float, (glm::qualifier)0> const&)'
/home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/bindings/glmBindings.o:glmBindings.cpp:function _wrap_fma: error: undefined reference to 'glm::vec<3, float, (glm::qualifier)0> glm::fma<glm::vec<3, float, (glm::qualifier)0> >(glm::vec<3, float, (glm::qualifier)0> const&, glm::vec<3, float, (glm::qualifier)0> const&, glm::vec<3, float, (glm::qualifier)0> const&)'
/home/adam/openFrameworks/addons/obj/linux64/Release/ofxLua/src/bindings/glmBindings.o:glmBindings.cpp:function _wrap_fma: error: undefined reference to 'glm::vec<4, float, (glm::qualifier)0> glm::fma<glm::vec<4, float, (glm::qualifier)0> >(glm::vec<4, float, (glm::qualifier)0> const&, glm::vec<4, float, (glm::qualifier)0> const&, glm::vec<4, float, (glm::qualifier)0> const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/adam/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/luaExample] Error 1
make[1]: Leaving directory '/home/adam/openFrameworks/addons/ofxLua/luaExample'
make: *** [/home/adam/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

It seems like there is some issue with the syntax of those `glm::vec` objects in the file "glmBindings.cpp" which is generated by "generate_bindings.sh" 

Does the syntax `glm::vec<2, float (glm::qualifier)0)>` seem a bit funny to you?

**Comment by Jonathhhan** [comment]
I have exactly the same Issue with Ubuntu 18.04 an 20.04 (and it was working before with 18.04). Maybe I need to downgrade a library?

**Comment by danomatika** [comment]
Does it throw this error when building in Debug mode only or Release as well? Maybe it's related to #58.

**Comment by Jonathhhan** [comment]
I used the Project Generator and tried to compiled with make (I guess it is release mode then).

**Comment by Jonathhhan** [comment]
The Lua example (and compiling the Ofelia external) does work with OF 0.10.1. and ofxLua 1.3.7. The Ofelia example and the Ofelia Emscripten example also work with of 0.11.2 and ofxLua 1.4.3, but not the Lua example and compiling the Ofelia example (with ofxOfelia which needs ofxLua) (all tested with Ubuntu 20.04).

**Comment by adammccartney** [comment]
Following the thread above #6397 - it looks like it might be an issue with the default constructors. 

It seems like the default constructors might need default values. Currently, the `./swig/glm/*.i` files used to generate the bindings for the of API contain default constructors that are implicitly defined. The issue might be resolved if they are replaced with user-defined initializer values. I can have a crack at a fix...

**Comment by adammccartney** [comment]
seems like it might be related to https://github.com/danomatika/swig-openframeworks/issues/23

issue is likely with swig as you say rather than ofxLua

**Comment by danomatika** [comment]
>It seems like the default constructors might need default values. Currently, the ./swig/glm/*.i files used to generate the bindings for the of API contain default constructors that are implicitly defined. The issue might be resolved if they are replaced with user-defined initializer values.

This is a good idea.

**Comment by danomatika** [comment]
This particular problem is not due to constructors. It looks like the `glm::fma()` function no longer has a vector template implementation and is scalar only now. This must have changed in a glm update as is perhaps a bug as the comments indicate it should work with vector types as well. This is why the linker complains about not finding vec2, vec3, and vec4 `fma` implementations. The fix is to only bind `fma(float, float, float)` and not the vector versions.

**Comment by danomatika** [comment]
The quick fix is to comment out the line with `FLOAT_SCALAR_OR_VECTOR_3_PARAMS(fma);` in `swig/glm/functions.i` and regenerate bindings.

**Comment by Jonathhhan** [comment]
@danomatika thank you very much. Now I can compile the LuaExample and the Ofelia external with OF 0.11.2 and ofxLua 1.4.3.

**Comment by danomatika** [comment]
@adammccartney Also, your point about the constructors helped me to find the fix for #23 which is to add `#define GLM_FORCE_CTOR_INIT` to glm.i.

**Comment by danomatika** [comment]
Now fixed with updated bindings in ofxLua 1.4.4.

**Comment by adammccartney** [comment]
> @adammccartney Also, your point about the constructors helped me to find the fix for #23 which is to add `#define GLM_FORCE_CTOR_INIT` to glm.i.

cool, happy to help - your code is clean and the README files are very well written, so it's easy enough to navigate and make sense of what's going on!
